module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.activities = [
    'Archery',
    'Badminton',
    'Baseball',
    'Basketball',
    'Beach Volleyball',
    'Beekeeping',
    'Birdwatching',
    'Bodyboarding',
    'Canoeing',
    'Capture the Flag',
    'Cricket',
    'Cross-country',
    'Skiing',
    'Cycling',
    'Diving',
    'Dodgeball',
    'Dragon Boat Racing',
    'Fishing',
    'Football',
    'Frisbee',
    'Hiking',
    'Hopscotch',
    'Horseback Riding',
    'Ice Skating',
    'Kayaking',
    'Kite Flying ',
    'Landscape Painting',
    'Lawn Bowling',
    'Mountaineering',
    'Outrigger Canoeing',
    'Rock Climbing',
    'Rowing',
    'Sailing',
    'Skateboarding',
    'Skiing',
    'Skipping Rope',
    'Snorkelling',
    'Snowboarding',
    'Soccer',
    'Surfing',
    'Swimming',
    'Tennis',
    'Tobogganing',
    'Trampolining',
    'Windsurfing'
]
